name: build-xs-melodic

on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
      - devel

defaults:
  run:
    shell: bash

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: main, NOT_TEST_BUILD: true}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone core and remove CATKIN_IGNOREs
        run: |
          git clone --branch devel https://github.com/Interbotix/interbotix_ros_core.git
          rm interbotix_ros_core/interbotix_ros_xseries/CATKIN_IGNORE
          rm interbotix_common_toolbox/interbotix_moveit_interface/CATKIN_IGNORE
          rm interbotix_xs_toolbox/CATKIN_IGNORE
      - name: Create src directory for xs
        run: |
          mkdir src
          mv interbotix_ros_core src
          mv interbotix_common_toolbox src
          mv interbotix_xs_toolbox src
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
